### ISSUE TITLE
about the details of sturcture learning experiment 

### ISSUE THREAD

**Issue by shumanzhuang** [likuanppd/STABLE#2]
Hi, thanks for sharing the code! I would like to ask for some details about the structure learning experiment.
In Table 3 you showed the number of total removed edges, removed adversarial edges, and removed normal edges. How can we obtain which edges are normal and which are adversarial in the adjacency matrix? I don't find keys for adversarial edges in the properties of the meta dataset, or I am missing them?
I am doing experiments with the meta dataset but I am troubled by this problem, if you could release the details or the code I would be very grateful!

**Comment by likuanppd** [comment]
Hi, thanks for you interests!

If the edges pruned by STABLE are originally in the clean graph, they are normal edges. Otherwise, they are adversarial edges. This experiment demonstrate with the same number of pruning, STABLE can remove more adversarial edges than Jaccard and GNNGuard.

**Comment by shumanzhuang** [comment]
I get it, thank you very much!
